export const PLAYER_MAXIMUM_HEALTH = 100;
export const PLAYER_MAXIMUM_STAMINA = 100;
export const PLAYER_COLLISION_RADIUS = 5;

export const PLAYER_WALKING_SPEED_PIXELS_PER_SECOND = 96;
export const PLAYER_ROLLING_SPEED_PIXELS_PER_SECOND = 210;
export const PLAYER_SPEED_WHILE_ATTACKING_PIXELS_PER_SECOND = 26;

export const ROLL_DURATION_SECONDS = 0.3;
export const ROLL_INVULNERABLE_SECONDS = 0.22;
export const ROLL_STAMINA_COST = 30;

export const STAMINA_RECOVERY_PER_SECOND = 46;
export const STAMINA_RECOVERY_DELAY_SECONDS = 0.45;

export const INVULNERABLE_SECONDS_AFTER_TAKING_DAMAGE = 0.85;
export const KNOCKBACK_FRICTION_PER_FRAME = 0.86;

export const SLICE_DAMAGE = 13;
export const SLICE_DURATION_SECONDS = 0.26;
export const SLICE_REACH_PIXELS = 13;

export const CRUSH_DAMAGE = 22;
export const CRUSH_DURATION_SECONDS = 0.42;
export const CRUSH_REACH_PIXELS = 15;
export const CRUSH_STAMINA_COST = 15;

export const PIERCE_DAMAGE = 10;
export const PIERCE_DURATION_SECONDS = 0.18;
export const PIERCE_REACH_PIXELS = 18;

export const MAXIMUM_EQUIPPED_RELICS = 3;
export const HEALTH_RESTORED_ON_ROOM_CLEARED = 18;
