export const DOOR_LANE_HALF_WIDTH_TILES = 2;
export const DOOR_LANE_DEPTH_TILES = 4;

export const SMALLEST_SOLID_PROP_WIDTH = 14;
export const SOLID_PROP_BASE_HEIGHT_PIXELS = 8;
export const SOLID_TREE_TRUNK_WIDTH_PIXELS = 14;
export const SOLID_TREE_TRUNK_HEIGHT_PIXELS = 10;
export const SOLID_LANDMARK_BASE_HEIGHT_PIXELS = 14;
